serverAddr = "172.207.250.61"
serverPort = 7000
auth.token = "fuck_njfu_lib_frp_token_2026"

[[proxies]]
name = "njfu_direct_api"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3001
remotePort = 3002
